on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'I want to manually trigger a PyPi push, without publishing a GitHub release (recommended)'
        required: true
        type: choice
        options:
          - Yes
  release:
    types: [created]

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/coc.py
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade build
    - name: Build
      run: |
        python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
